### ISSUE TITLE
[2.0.0]Le jeu ne se lance pas (crash)

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#11]
Salut, le jeu ne lance pas donc pourriez-vous m'aider a tout faire marcher ?
Voici le log : http://pastebin.com/Kkb3WQf9
Mon remote_info.json : http://dl.hotcube.xyz/remote_info.json
Et mon dossier maven (parce que j'utilise l'updater 2.0.0) : http://dl.hotcube.xyz/maven/
Merci d'avance

**Comment by robin4002** [comment]
Salut,
Si tu ne veux pas de whiteList il ne faut pas mettre la valeur sur rien mais complètement retirer la ligne.

**Comment by vrackfall** [comment]
Ok j'ai testé, mais ça  a encore crash. Voici le log : http://pastebin.com/sX1q1AU8
Mais sinon ça sert a quoi le "inheritsFrom": "1.7.10", étant donné que j'utilise forge et liteloader, je fait quoi avec ?

**Comment by robin4002** [comment]
Le inheritsFrom c'est un truc du launcher pour dire qu'il devra utiliser les bibliothèques qui se trouve dans le jar 1.7.10 en plus de celle indiqué.
Sur le deuxième crash il y a un problème avec le changelog, c'est étrange. Je vais voir de mon côté, pour l'instant je n'ai pas encore publié la 2.0, en fait je n'ai même pas eu le temps de tester que tout fonctionne sur le launcher.

**Comment by vrackfall** [comment]
Bon ben, j'ai juste laissé le champ du changeLog vide pi ça a marché.
De toute façon j'en avais pas besoin.
Le jeu se lance parfaitement.

**Comment by robin4002** [comment]
Étrange ça. Je peux avoir le rapport de crash complet ?

**Comment by vrackfall** [comment]
Ok, le voici, j'te préviens il est long, et c'est pas les mods le problème : http://pastebin.com/pKy04JtV

**Comment by robin4002** [comment]
Vraiment ?
```at com.wirsbo.main.ClientEvents.onWorldLoad(ClientEvents.java:70)```
```java
  @SubscribeEvent
  public void onWorldLoad(WorldEvent.Load event)
    throws IOException
  {
    File fileFolderConfig = new File("config/betterrain");
    boolean bc = fileFolderConfig.mkdir();
    File fileConfig = new File("config/betterrain/config.txt");
    if (!fileConfig.exists())
    {
      fileConfig.createNewFile();
      BufferedWriter bw = new BufferedWriter(new FileWriter(fileConfig));
      bw.write("rain_min=" + rain_min);
      bw.newLine();
      bw.write("rain_max=" + rain_max);
      bw.newLine();
      bw.write("rain_soundMultiplier=" + rain_soundMultiplier);
      bw.newLine();
      bw.write("rain_random=" + rain_random);
      bw.flush();
      bw.close();
    }```
Le mod n'utilise pas Minecraft.getMinecraft().mcDataDir, il prend directement le dossier courrant (donc .minecraft au lieu de .minecraft/modpacks/<nom du pack>).
Et il utilise  fileFolderConfig.mkdir() au lieu de fileFolderConfig.mkdirs(), donc si le dossier .minecraft/config n'existe pas (ce qui est le cas si Forge n'a pas été lancé une fois sur un profil Forge normal) le dossier betterrain ne pourra pas être créé le donc le fichier de config non plus.

J'ai déjà regardé si on pouvait changer le dossier actuel, j'ai trouvé ça : http://stackoverflow.com/a/13981910
Mais cela ne fonctionnera que si le mod utilise getAbsoluteFile ce qui n'est pas le cas :/

Le seule solution est que les moddeurs utilisent Minecraft.getMinecraft().mcDataDir au lieu d'utiliser directement le dossier courant (utiliser le dossier courant n'est pas une bonne chose d'ailleurs car cela cause des problèmes avec l'option du launcher qui permet de changer le dossier du jeu et donc également avec mon installateur).

**Comment by vrackfall** [comment]
Ok merci, j'vais essayer de faire fonctionner tout ça ou simplement juste l'enlever.

**Comment by vrackfall** [comment]
Bon ben ça marche, merci :)
