### ISSUE TITLE
whitelist.txt vers whitelist.json

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#12]
Salut, serait-il possible de changer le système de whitelist ? 
Je m'explique : 
Au-lieu d'être un fichier txt la whitelist serait un fichier xlsx.
Pourquoi ?
L'updater lirait seulement la première colonne et on pourrait mettre ce qu'on veut dans les autres colonnes. Comme ça on pourrait repérer plus facilement les mods qu'on veut modifier lors d'une MàJ.
Exemple : 
[whitelist.xlsx](https://github.com/FFMT/ModPackInstaller/files/71267/whitelist.xlsx)

Merci d'avance

**Comment by robin4002** [comment]
Plutôt du json alors. 
```{
   "nomdumod":"md5",
   "nomdumod2":"md5 2"
}```
C'est vrai que c'est plus pratique pour repérer le mod.

**Comment by vrackfall** [comment]
Bah, qqch qui marche ...

**Comment by robin4002** [comment]
Pourquoi ?
Le json peut très bien être fait à la main. De plus je ne vois pas l'intérêt de mettre les jars sur le serveur, ça prendra de la place pour rien.

**Comment by vrackfall** [comment]
Les jars ? Quels jars ? Ceux des mods ?

**Comment by robin4002** [comment]
Oui, ceux des mods que tu vas autoriser. Si tu veux générer le json automatique il faut bien qu'il soit présent.

**Comment by vrackfall** [comment]
Nan mais les mods que j'utilise y sont déjà dans le dossier sync/mods/1.7.10 (pas besoin d'les avoir en double)donc juste pour mieux expliquer :
T'as un dossier whitelist dans ton serveur web (pas dans le dossier sync), dedans tu met un index.php.
Une des lignes du fichier te dit ou est le dossier contenant les mods (dl.hotcube.xyz/sync/mods/1.7.10/ pour moi).
Le php génère une liste de md5 en txt ou en json ...
Pi après t'as plu qu'a indiquer a ton remote_info.json ou est ton dossier "whitelist" si tu veux l'activer.
Voilà, bon après t'est pas obliger d'faire ça ....

**Comment by robin4002** [comment]
Heu ... What ?
Pourquoi tu utilises la whitelist comme ça ?
Si tes mods sont dans sync/mods/1.7.10 ils sont déjà téléchargé par l'installateur.

La whitelist c'est pour autoriser des mods non présent de base dans le modpack.

**Comment by vrackfall** [comment]
Ha ouai j'le savais pas, donc on oublie le index.php. 
Mais ça sert aussi a  empêcher d'autres mods d'être présents, J'me trompe ?

**Comment by robin4002** [comment]
Non, de base tous les autres mods sont interdits. La whitelist permet juste d'autoriser d'autres mods.

**Comment by vrackfall** [comment]
Ok, c'est que depuis l'début j'ai un p'tit problème avec l'updater : Les vieux mods dans le .minecraft ne sont pas supprimés (ceux que j'ai supprimé de mon dossier sync). J'utilise pas la whitelist mais je sais pas d'ou vient le bug.

**Comment by robin4002** [comment]
What ? complètement inutile tout ça.
Les fichiers non présent dans le dossier sync sont supprimés : 
```C:\Users\Robin\AppData\Roaming\.minecraft\modpacks\nhg\mods\FFMT-libs-universal-1.6.2.152-mc1.8.8.jar a été supprimé. Son MD5 était 23c1d715010a89591fdf580c840b2862
Téléchargement du fichier http://dl.mcnanotech.fr/hungergames/installateur/sync/mods/FFMT-libs-universal-1.6.2.153-mc1.8.8.jar vers C:\Users\Robin\AppData\Roaming\.minecraft\modpacks\nhg\mods\FFMT-libs-universal-1.6.2.153-mc1.8.8.jar (MD : 2e00285ec8bab41226614ab800d05797)```
Je ne sais pas pourquoi ça ne fonctionne pas chez toi.

**Comment by vrackfall** [comment]
Mouais, moi non plus j'comprends pas, xD

**Comment by vrackfall** [comment]
Mais est-ce que l'updater est capable de lire la taille des fichiers dans le .minecraft, ex pour voir s'ils sont a jour avec ceux en ligne ? (J'ai un pack de ressource que j'modifie de temps en temps, sans toutefois changer son nom)

**Comment by robin4002** [comment]
Il se base sur le md5 (qui est différent si tu modifies le fichier).
Normalement il devrait le télécharger si tu modifies le fichier.

**Comment by vrackfall** [comment]
Normalement, mais c'est pas l'cas, (P'tre que ça marche si j'active la whitelist, jsp)

**Comment by robin4002** [comment]
Le fait que la whitelist soit on ou off n'a pas d'influence sur ça.
Je viens de tester de mon côté, j'ai mit un fichier text nommé test.txt contenant "text" dans le dossier sync/resourcepacks il me l'a téléchargé.
Je l'ai modifié pour ajouter une deuxième ligne contenant "dgvdf gdg vdf" (oui j'ai écrit n'importe quoi à l'arrache), j'ai relancé le jeu et voila : 
```Téléchargement du fichier http://dl.mcnanotech.fr/hungergames/installateur/sync/resourcepacks/test.txt vers C:\Users\Robin\AppData\Roaming\.minecraft\modpacks\nhg\resourcepacks\test.txt (MD : 36ccf665a1d61c466b8a078a68efad36)```
Il a téléchargé le nouveau et écrasé l'ancien. Je ne vois pas où est le problème.

**Comment by vrackfall** [comment]
Bon ben, ça doit marcher alors.
Merci 
(Tu peux fermer l'issue)

**Comment by robin4002** [comment]
Je la fermerai une fois que j'aurai passé la whitelist en json.

**Comment by vrackfall** [comment]
Ok, thanks
