### ISSUE TITLE
Run the launcher

### ISSUE THREAD

**Issue by robin4002** [FFMT/ModPackInstaller#13]
An new option to run the launcher when the installation is finish.

**Comment by vrackfall** [comment]
Un autre affaire qui s'rait cool aussi (et ça marcherait) : 
Au début de l'installation : si le fichier profiles.json n'est pas présent dans le .minecraft, l'installateur en crée un. Comme ça plus besoin de lancer l'install deux fois (une fois avant et l'autre après d'avoir lancé minecraft). Mais bon, c'est qu'une idée et puis, j'ai déjà réussi qqch comme ça mais avec un batch, et ça marchait.

**Comment by robin4002** [comment]
Le fichier profiles.json est sensé déjà exister puisque Minecraft doit déjà être installé.

**Comment by vrackfall** [comment]
J'avais réussi a créer un installateur en batch, il faudrait juste faire qqch pareil pour le votre et y rajouter des options pour OS X et LIN (il marcherait que quand le jeu n'est pas installé) :  
1- Téléchargment de minecraft.exe sur le bureau
2- Téléchargement d'un profiles.json vide (ou presque) dans le bon dossier
3- Téléchargment d'un launcher-profiles.json (vide ou presque) dans le bon dossier

**Comment by robin4002** [comment]
Non mais l'installateur part du principe que le jeu est déjà installé donc je prévois pas de faire une tel fonctionnalité.
De toute façon si le joueur veut rejoindre un serveur Minecraft dans 99,99 % des cas il a déjà Minecraft.

**Comment by vrackfall** [comment]
Ouai, c'est vrai, bon ben c'pas grave
Merci quand même, bonne continuation et bon temps des fêtes
