### ISSUE TITLE
Compatibilité pour le season mod 

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#14]
Salut, la nouvelle version du mod season mod est enfin sortie, compatible client et serveur, (on a le droit de l'inclure dans nos modpacks) : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285986

Or, pour son bon fonctionnement ce "mod" (c'en est pas vraiment  un) doit être placé dans le dossier par défaut du jeu ".minecraft/....". J'vais pas expliquer tous les étails, mais en fait j'vous demanderais d'ajouter ça a l'installateur : 
un dossier pour télécharger ce qui va directement dans le .minecraft (ça fonctionnerais comme le dossier sync, avec une nouvelle ligne comme le "syncdir" dans le remoteinfo.json)

Et sinon y'a t-il une façon d'ajouter des arguments java au jeu en passant par un mod ?

**Comment by robin4002** [comment]
Hors de question d'installer des fichiers directement dans le dossier .minecraft. C'est la mauvaise idée parfaite pour créer des soucis entre les différents modpack et le jeu de base.

Les moddeurs ont juste faire leurs mods correctement.

Et non il n'est pas possible de modifier les arguments java via un mod, mais c'est possible via l'installateur.
J'ai regardé vite fait le bordel de ce mod, en mettant comme argument : -javaagent:modpacks/nomdumodpack/PMLCore/PMLPremain.jar=-MCSide:Client
et les fichiers directement dans le dossier du modpack ça pourra peut-être fonctionné.
Reste à voir s'il va chercher le mod au bon endroit, mais ça ce n'est pas sûr.
Au pire dire à l'auteur du mod que son bordel ne permet pas d'utiliser l'option game directory du launcher.

**Comment by vrackfall** [comment]
Contre arguments, xD :  ce mod ne peux pas être lancé sans l'argument : 
-javaagent:.../PMLCore/PMLPremain.jar=-MCSide:Client
Donc le mod ne peux tout simplement pas créer des soucis avec les autres mods (surtout qu'il n'est même pas dans le dossier mods), mais bon après, c'est vous qui décidez.

Et puis, je vous aurais jamais contacter si j'aurais pas déjà tester le : 
 -javaagent:modpacks/HotCube/PMLCore/PMLPremain.jar=-MCSide:Client
avant, et ça marche pas donc, voici mon crash report : 
http://pastebin.com/ijH6UKkf

**Comment by vrackfall** [comment]
Je viens de damander a l'auteur s'il peux rendre tout compatible

**Comment by vrackfall** [comment]
[quote=The_WeatherPony;../../../members/The_WeatherPony;2602016-partial-modification-loader-pml-for-minecraft-a?comment=7]
[p]I can try to get that to play better for PML9.2, along with some other oddball issues.[/p]
[/quote]

**Comment by robin4002** [comment]
Pas faux. Mais franchement je n'ai pas envie de développer un hack pour chaque mod qui ne fait pas les choses correctement.

**Comment by vrackfall** [comment]
mais bon après, t'est pas obliger, y'aura surment un fix dans la version 9.2 de pml

**Comment by robin4002** [comment]
Sauf que ça va fix (en théorie) tous les autres mods souffrant du même problème. Donc comme je peux le faire autant le faire.
Là c'est juste une petite ligne qui change, c'est pas comme si je devais implémenté un nouveau répertoire sync qui envoie tout dans le .minecraft, ce qui m'aurait prit bien plus de temps à implémenter.

J'ai trouvé un moyen de get java qui fonctionne sur tous les pc, https://github.com/FFMT/ModPackInstaller/commit/27b384ba11dc54d900879801cae7962077519171 mojang utilise la même chose dans le launcher.
Maintenant il me reste à get les arguments du processus java, ça aussi je sais faire, je l'avais déjà fait dans un mod.

**Comment by robin4002** [comment]
Bon j'ai rapidement bricolé ce petit mod : 
```java
    @EventHandler
    public void init(FMLInitializationEvent event)
    {
        System.out.println((new File(".")).getAbsolutePath());
        System.out.println(Minecraft.getMinecraft().mcDataDir.getAbsolutePath());
    }
```
Actuellement ça print :
[22:38:17] [Client thread/INFO] [STDOUT]: [com.example.examplemod.ExampleMod:init:19]: C:\Users\Robin\AppData\Roaming\.minecraft\.
[22:38:17] [Client thread/INFO] [STDOUT]: [com.example.examplemod.ExampleMod:init:20]: C:\Users\Robin\AppData\Roaming\.minecraft\modpacks\demo

J'upload ma version modifier et on va voir.

**Comment by vrackfall** [comment]
Heu ok, ça a d'l'air cool mais pour le "stuff pml", ça ajoute quoi ?

**Comment by robin4002** [comment]
Bon en fait c'est mort, ma version modifié pour le lancement ne fonctionne pas :/
Pourtant j'utilise exactement la même commande que mc, mais ça ne veut pas.

**Comment by vrackfall** [comment]
Bon ben reste plus qu'a attendre la maj 9.2 de pml (partial modification loader)

**Comment by vrackfall** [comment]
Ok, c'est bon ça va marcher maintenant

**Comment by vrackfall** [comment]
A fermer
