### ISSUE TITLE
Le bouton "Lancer Minecraft"

### ISSUE THREAD

**Issue by FredericFernandes** [FFMT/ModPackInstaller#17]
J'ai un petit soucis avec ce bouton. J'ai vu dans ton code que tu avais mis en dûr le chemin pour lancer
Minecraft , 
Notamment l'utilisation du "Program Files (x86) " alors qu'une personne l'a peut être installé en Program Files ou dans ProgramData , voir même comme tu là dis dans une Clé USB .
Je ne suis pas dans la tête de mes joueurs , mais je veux juste leurs éviter un message d'erreur pour rien :)
Donc je me demande si il y a pas une possibilité de cacher le bouton ou de mettre une liste de chemin et le prog les tests un par un ?

**Comment by Superloup10** [comment]
Le chemin en dur qui passe par le "Program Files (x86) " ne concernent que ceux qui ont utiliser l'installateur de Minecraft pour windows. Pour tous les autres, c'est le launcher.jar qui se trouve dans le APPDATA qui est lancé.

**Comment by FredericFernandes** [comment]
Le truc c'est que moi je ne veux pas faire la police et donc j’accepte toutes les versions.
Donc pour ceux qui on une version crack on t'ils ce chemin qui existe ?

**Comment by robin4002** [comment]
Mojang a changé des choses au niveau de leur launcher récemment, j'ai déjà eu deux commentaires sur le tutoriel vidéo de l'installateur qui indiquait une erreur avec cette option. 
Je vais voir demain pour adapter le code et ajouter une option pour désactiver ce bouton.

**Comment by robin4002** [comment]
Il y a 3 launchers donc 3 cas possible :
* le launcher Java : c'est le plus vieux, il est sortie en même temps que la 1.6. C'est juste un petit bootstrap en java (et donc qui nécessite java pour fonctionner) qui télécharge le vrai launcher dans le dossier .minecraft et le fichier se nomme launcher.jar
* le launcher en C : sortie il y a un an maintenant, il télécharge sa propre version de java qu'il met dans un fichier nommé runtime et lance avec cette version de java le fichier launcher.jar qu'il télécharge dans le dossier game. Ici pas besoin d'avoir java installé sur le pc, et l'emplacement du launcher est variable (il dépend de où le launcher a été lancé).
* l'installateur msi : c'est exactement le launcher en C sauf que les fichiers sont mit dans le dossier C:\Program Files (x86)\Minecraft si le pc est en 64 bits ou C:\Program Files\Minecraft si le pc est en 32 bits. Ici l'emplacement du launcher est donc fixe.

Le cas qui cause problème est donc le deuxième, je vais faire en sorte que le launcher cherche la présence du fichier launcher.jar dans .minecraft, C:\Program Files (x86)\Minecraft et dans C:\Program Files\Minecraft, dans le cas où il ne le trouve pas je vais désactiver le bouton.
