### ISSUE TITLE
Updater et https

### ISSUE THREAD

**Issue by robin4002** [FFMT/ModPackInstaller#19]
L'updateur ne fonctionne pas en https mais l'installateur si.
Surement un problème avec des arguments en rapport avec l'https mit en place par le launcher.

**Comment by robin4002** [comment]
J'ai fouillé le code du launcher (recherche de ssl/tls dans le code) je n'ai rien trouvé. Ça risque d'être compliqué à déboguer.

**Comment by robin4002** [comment]
En fait le problème concerne aussi l'installateur et non uniquement l'updater.
Et il ne vient pas directement de l'installateur ou de l'updater, mais du fait que les certificats SSL let's encrypt signé par IdenTrust ne sont pas encore prit en charge dans la dernière version de Java pour Windows.
Sur la JVM que j'ai sous Linux je n'ai pas de problème.

http://stackoverflow.com/questions/34110426/does-java-support-lets-encrypt-certificates
Le problème sera normalement réglé avec Java 8 update 101.

**Comment by vrackfall** [comment]
JDK 8 Update 102 est sorti, le problème est-il réglé? Le sera-t-il?

**Comment by Superloup10** [comment]
Le problème de certificat SSL est effectivement corrigé depuis la build 101 de Java 8, mais il y a encore beaucoup d'utilisateurs qui utilisent une version antérieure du coup, c'est à Robin de corriger ça dans le code en ajoutant une option qui demandera l'endroit où est stocké le certificat SSL sur le serveur de l'administrateur du modpack.

**Comment by robin4002** [comment]
il est possible d'ajouter de force le certificat, mais il serait mieux que les utilisateurs mettent à jour Java.

**Comment by vrackfall** [comment]
Mouais, mais vu qu'au moins la moitié le feront pas ou le feront jamais, ça s'ras encore a toi d'tout faire marcher, oui c'est nul :(

**Comment by robin4002** [comment]
Garder une ancienne version de Java est dangereux pour le système et Java possède une appli qui vérifie les mises à jour et demande de mettre à jour s'il y en a une. Donc bon ...

**Comment by vrackfall** [comment]
e.g.: J,ai dit une dizaine 'fois a mon père d'mettre a jour son java, il l'a pas encore fait, donc imagine avec ceux qui l'on pas fait d'puis java 6

**Comment by utybo** [comment]
Java 6 (et 7) sont dépréciés et même dangeureux à l'utilisation depuis longtemps... Par dangeureux je veux dire qu'il peut y avoir des failles de sécurité un peu partout...

**Comment by Superloup10** [comment]
C'est pas ça qui va les motiver à ce mettre à jour, il faudrait déjà que Minecraft passe sur Java 8 pour la configuration minimale, ça aiderait pas mal.

**Comment by vrackfall** [comment]
Mouais, l'installateur d'minecraft sous windows a déjà une version précise de java, mais ça doit faire un bout qu'elle a pas été maj. Comme quoi Microsoft délaisse peu a peu son gout au café (vous comprenez l'allusion? :) ).

**Comment by robin4002** [comment]
La version de Java intégré avec l'installateur de Minecraft est isolé du reste du système, elle ne peut pas être utilisé dans le navigateur ni avec d'autres programmes.
Si Mojang garde cette version, c'est à cause des utilisateurs W10 ayant un chipset Intel de la génération sandy bridge ou plus ancien.

**Comment by vrackfall** [comment]
Mouais, et y peuvent pas l'mettre a jour a cause d'ça?
