### ISSUE TITLE
mauvaise gestion des threads

### ISSUE THREAD

**Issue by robin4002** [FFMT/ModPackInstaller#20]
La barre de progression n'est pas géré correctement.
Voir : http://technologyatyourreach.blogspot.fr/2011/11/exception-in-thread-awt-eventqueue-0.html

**Comment by utybo** [comment]
Ceci https://docs.oracle.com/javase/8/docs/api/index.html?javax/swing/ProgressMonitor.html pourrait être utile, mais les ProgressMonitor sont des boîtes de dialogue *à part entière*.

**Comment by robin4002** [comment]
Il suffit de faire comme ceci :
```java
        EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                // Code de mise à jour de la barre
            }
        });```
Mais comme j'utilise la barre dans d'autre classe ça va être un peu l'anarchie à faire. Je vais réfléchir à comment adapter le code.
