### ISSUE TITLE
A ajouter a l'installateur ?

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#23]
Salut, 
Il y'a des fichiers log dans un des répertoires que je dois synchroniser (avec fichiers a supprimer .... vous connaissez le tralala). Or, ces 4 ou 5 fichiers log là doivent pas être supprimer même s'il servent a rien.
Et puisqu'ils sont modifier a chaque lancement du jeu, leurs md5 sont toujours modifiés (il en va de même pour d'autres fichiers de config dans d'autre qui pourraient être modifiés par les utilisateurs de l'installateur, ça aiderait aussi pour les préconfiguration)
~~Pourriez-vous ajouter ça au code pour la whitelist : 
Lorsque la lgine de la whitelist n'a pas de md5, ne pas supprimer le fichier (Comme quand le md5 client-serveur correspond).~~

Oui ça fait un installateur très compliqué, xD

*Désolé pour mes fautes, j'me corrige pas quand j'tappe a l'ordi, surtout qu'j'suis québécois

Merci d'avance

**Comment by robin4002** [comment]
Il faudrait plutôt demander à l'auteur des mods de déplacer ces logs, se baser sur le nom pour la whitelist serait une faille de sécurité majeur.

**Comment by vrackfall** [comment]
Ouai la j'avoue que c'est plus une si bonne idée d que ça.

**Comment by robin4002** [comment]
Ça me tente pas vraiment, ça va être un gros bazar à implémenter pour pas grand chose au final.

**Comment by utybo** [comment]
C'est surtout une erreur de conception de la part du moddeur qui met ses logs n'importe où à mon avis

**Comment by vrackfall** [comment]
Ok pas grave, j'vais attendre la réponse du moddeur.... maudit qu'c'est compliquer la vie
