### ISSUE TITLE
La fonction trim ne marche pas

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#24]
//////////  #:https://github.com/FFMT/ModPackInstaller/commit/eb443bdaf81b7192ebb28d7f9f1a762d757a3d26 //////////  
Salut les bidouilleurs,
juste pour informer que les espaces entre les virgules que @robin4002 avait ajouter [ici ](https://github.com/FFMT/ModPackInstaller/commit/eb443bdaf81b7192ebb28d7f9f1a762d757a3d26) pour la ligne "syncDir"  du remote_info.json ne marche pas (a moins que la version que j'utilise soit un peu en retard, j'ai la 2.1.3). Le truc c'est que la ligne "syncDir", c'est un peu illisible sans les espaces entre les ",".
 
Pourriez-vous corriger ça ? 
Merci d'avance

**Comment by robin4002** [comment]
Je n'ai pas encore publié la version contenant ce commit.
