### ISSUE TITLE
Changelog Size

### ISSUE THREAD

**Issue by FredericFernandes** [FFMT/ModPackInstaller#25]
Bonjour à tous.
J'ai un trouvé un petit problème, au niveau de la fenêtre qui affiche le contenu du fichier changelog.
Le texte qui y est affiché n'a pas de retour à la ligne en fonction de la taille de la JFrame. Donc, la fin des longues phrases n'est pas affichée et sont coupées par la JFrame. 
Cordialement.

**Comment by utybo** [comment]
Bonjour,
Je n'arrive pas à trouver de quelle JFrame tu parles, pourrais-tu m'indiquer comment tu y accèdes?

**Comment by FredericFernandes** [comment]
Oui peut être j'ai pas lu le code source à ce niveau là. Et je n'y accèdes pas , je lance juste le luncher de minecraft avec une mise à jour des mods.
Et le texte contenu dans le fichier changelogs ne va pas à la ligne en fonction de la fenêtre où il est.

**Comment by utybo** [comment]
Voilà, y'a plus qu'à merge et c'est bon

**Comment by FredericFernandes** [comment]
Merci, J'att la release avec impatience :)

**Comment by robin4002** [comment]
Je change juste le numéro de build et je publie la version 2.2.1 ;)

**Comment by FredericFernandes** [comment]
Test
