### ISSUE TITLE
Changelog Size V2 

### ISSUE THREAD

**Issue by FredericFernandes** [FFMT/ModPackInstaller#27]
Salut, c'est encore moi, le relou :)
Sais juste pour dire que le changelog qui est affiché dans l'InstallFrame est correctement affiché, mais pas dans l'Updater du luncher en cas de MaJ.
Ce qui me fait venir à cette question , comment il faut faire pour une mise à jour de l'installateur ?
Car l'installer par dessus a le résultat précédent .  
L'installateur peut t'il détecter qu'un installateur est installé ? Et le supprimer ainsi que tous ces fichiers de config pour la nouvelle version ? 

Cordialement.

**Comment by robin4002** [comment]
Salut,
Dans le fichier remote_profile.json dans la partie libraries il y a la version de l'updater.

**Comment by FredericFernandes** [comment]
D'accord !! 
Il y a ici à changer aussi, merci de l'info j'avais oublié se détaille important.
