### ISSUE TITLE
Ajout d'un nouveau mode de fonctionnement e l'installateur/l'updater, le mode "développeur"

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#28]
Salut,
Je viens d'avoir une idée qui pourrait bien améliorer le fonctionnement de l'installateur/l'updater lorsque c'est un des administrateur qui l'utilise.

"Le mode développeur" permettrait a l'administrateur du modpack de désactiver certaines fonctionnalités pour faire des test sans affectés les autres joueurs (comme la synchronisation des fichiers, dont ceux de configuration par exemple, pour qu'il puisse mieux tester le modpack), mais seulement pour son utilisation (donc l'utilisation du modpack par les autres utilisateur du modpack resterait restreinte).

Comment ça pourrait marcher?

Un fichier de configuration client et un autre serveur : 

> dev_mode_client.json:
> `{
>     "credantials": {
>         "username": "MonNom",
>         "password": "MonMotDePasse",
>         "userip": "AdresseIpDeLAdministrateurDuModPack",
>         "md5": 
>     },
>     "override": {
>         "_comment": "Par exmple, si les syncDir a du contenu dans le remote_info.json, l administrateur peut en enlever, mais seulement pour lui",
>         "remote_info.json": {
>             "install": {
>                 "syncDir": "mods"
>             }
>         }
>     }
> }`
> 
> dev_mode_remote.json:
> `{
>     "credantials": {
> "Md5DeMonNom+Md5DeMonMotDePasse+Md5DeAdresseIpDeLAdministrateurDuModPack"
>     },
> }`

sinon pour que ça marche faudrait aussi ajouter l'adresse du dev_mode_remote.json dans le remote_info.json, et certaine ligne du fichier ne pourrait pas être modifiées.

Merci d'avance

**Comment by utybo** [comment]
Autant pouvoir faire des tests en local, un mode developpeur online pose
des soucis de sécurité

**Comment by vrackfall** [comment]
Justement, donc il faut le protéger, et encoder  (le mode ne marche que si l'ip de l'ordinateur coincide avec celle de l'ordinateur du joueur)

**Comment by Superloup10** [comment]
Ton système ne fonctionne que si l'adresse ip du pc est fixe, hors à l'heure actuelle, les adresses ip sont pratiquement toutes dynamiques.

**Comment by robin4002** [comment]
Autant faire un deuxième installateur pour le développement non ?

**Comment by vrackfall** [comment]
@Superloup10
Ah ouai, j'y avais pas penser, ...

@robin4002 
Heu, j'y avais pas penser non plus... Mais bon, je fait que donner des id/es (depuis le d/but on va dire, xD). A toi de voir ce qui est le plus facile a coder (p.s.: j'etais sous un pc sans accent, en vacnace tr's loin d,chez moi)

**Comment by robin4002** [comment]
à la limite pour ce second installateur de dev, pour le sécuriser un peu je pourrai ajouter une whitelist d'utilisateur par uuid. Ça pourra être une fonctionnalité utile.

**Comment by vrackfall** [comment]
Mouais, tant qu'ça marche, t'es pas obliger d'le faire non plus
