### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by sam543381** [FFMT/ModPackInstaller#4]
Voilà un bout de temps que j'ai tester votre launcher, et je voilà que je le relance et qu'une erreur survient :
http://pastebin.com/N94nzQv1

Voilà d'où ça vient.
https://github.com/FFMT/ModPackInstaller/blob/master/src/main/java/fr/minecraftforgefrance/updater/Updater.java#L133

L'exécutable : http://samsamcraft.url.ph/installer/Samsamcraft-Installer-Updater.jar

Je n'utilise plus ce launcher et la version que j'avais utilisé doit être un peu vieille, ce n'est donc pas grave si vous le problème n'est pas cerné. En fait je fais une issue juste histoire de signaler le bud (si ça ne vient pas de moi).

Ah et tant que j'y suis j'ai une suggestion. Quelqu’un qui voudrait cheat n'aurait qu'à copier les mods du launcher (.minecraft/modpacks/<launcher>) pour les lancer dans une installation de forge classique et rajouter xray, j'avais pensé que pour augmenter la sécurité de ce launcher l'idée serait de rajouter un mod serveur ou un plugin qui se chargerait via un sorte de sesssionID de vérifier que le client se connecte bien avec l'installeur. Si non tout simplement kick le client.

**Comment by robin4002** [comment]
Rien à voir avec l'installateur, c'est forge qui ne se lance pas car tu utilise une ancienne version de forge et que tu as java 8. Suffit d'ajouter ce mod : http://files.minecraftforge.net/LegacyJavaFixer/legacyjavafixer-1.0.jar

Pour la sécurité, tu peux aussi ajouter un mod perso qui crash si il n'est pas dans le dossier .minecraft/modpacks/<nom de ton modpack>
(suffit de mettre : 
````java
if(!Minecraft.getMinecraft.mcDataDir.getPath().contains("modpacks/<nom de ton modpack>"))
{
     FMLCommonHandler.instance().handleExit(0);
}
