### ISSUE TITLE
ModPackInstaller avec liteloader et forge ?

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#5]
Salut les développeurs, cet installateur est-il compatible avec liteloader et forge en même temps. Si oui comment ?
Merci d'avance

**Comment by robin4002** [comment]
Salut,
C'est surement possible. Il faudrait comparer le fichier json d'un profile liteloader pour voir ce qu'il ajoute et repporter ça dans le fichier json de ton serveur. Et également gérer le téléchargement du fichier jar de liteloader.

**Comment by vrackfall** [comment]
Heu... tu pourrais me le faire parce que moi...

**Comment by robin4002** [comment]
http://dl.mcnanotech.fr/FFMT/installer/resources/
À tester. Théoriquement c'est ok, j'ai comparé les fichiers de profil il y a juste un argument de lancement en plus et la bibiothèque de liteloader.

**Comment by vrackfall** [comment]
Ok merci si c'a marche je te passe mon installateur et je te fais tester mon serv après

**Comment by vrackfall** [comment]
Heu j'ai un problème avec l'installateur : C'a me dit que je suis pas connecter a internet et pourtant je le suis.

**Comment by robin4002** [comment]
Il n'arrive pas à lire ton fichier xml. Ce problème arrive quand aucun fichier n'est présent dans le dossier sync.

**Comment by vrackfall** [comment]
Quel fichier xml ? Parce qe si c'est celui qui devrait être générer par le fichier php ben c'a marche pas

**Comment by robin4002** [comment]
Oui c'est celui généré par le fichier php.
Vérifie qu'il y a bien quelque chose dans le dossier sync. Si il est vide, le fichier xml n'ai pas généré correctement.

**Comment by vrackfall** [comment]
Le fichier xml n'est pas générer correctement mais c'a vient pas des permissions et non plus du contenu de son emplacement

**Comment by robin4002** [comment]
La version de php est à jour ?

**Comment by vrackfall** [comment]
Heu non mais  c'est la 5.3

**Comment by robin4002** [comment]
Je ne sais pas d'où ça peut venir :/ Essaye avec un autre hébergeur sinon

**Comment by vrackfall** [comment]
Ouai, j'en essaille d'autres...

**Comment by vrackfall** [comment]
Oh yeah c'a marche parfaitement reste plus qu'a modifier et tester l'installeur
