### ISSUE TITLE
Crash à la fin de l'installation

### ISSUE THREAD

**Issue by DJDaemonix** [FFMT/ModPackInstaller#6]
Bonjour,

J'ai rencontré un crash qui eu lieu vers la fin de l'installation de Rexacraft sur le Mac Mini de mon père.
Le crash n'a eu aucune incidence sur l'installation du modpack, et le jeu s'est lancé proprement.

Crash-log (très long/complet/(in)utile) : http://puu.sh/hrDCS/f954d200b5.txt

Merci,
DJ Daemonix

**Comment by robin4002** [comment]
La version de Java 6 d'Apple est une version différente de la version officiel, le crash doit surement être du a ces différences. Le mieux serait d'utiliser la version d'oracle de Java 8 car de toute façon Java 6 est mort.

**Comment by DJDaemonix** [comment]
J'ai pensé ça, mais après installation de Java 8, aucune différence n'a pu être sentie.

**Comment by robin4002** [comment]
Vérifie que Java 8 est bien mit par défaut. Il n'est pas impossible que l'installateur continu à utiliser Java 6 malgré la présence de Java 8.
