### ISSUE TITLE
Optimisation des configs (amélioration de l'install), oui je sais.....

### ISSUE THREAD

**Issue by vrackfall** [FFMT/ModPackInstaller#7]
Salut, 
Je pense avoir une super idée, qui simplifierai beaucoup le jeu, pour cet installateur que vous pourriez peut être réalisé : 
Un dossier /_configs/ (qui serait supprimer a la fin de l'install) dans le dossier sync ou l'on pourrait choisir quoi installer a partir de l'installateur (par exemple pour les config des mods opu du clavier qui sont souvent conflictuel d'une personne a l'autre, surtout a cause du "clavier par pays")

Merci d'avance, vive les vacances et vive le temps libre

**Comment by robin4002** [comment]
En gros tu veux que certaines config soit synchroniser et pas d'autres ? Tu peux déjà gérer ça avec l'option syncDir il me semble, logiquement il suffit de mettre config/nomDuFichier.cfg pour que celui-là soit synchronisé et pas les autres.
Ou alors ne mets pas du tout le dossier config dans syncDir, les fichiers ne seront que téléchargés lors de la première installation et non à chaque lancement.

**Comment by vrackfall** [comment]
Non,  j'ai du mal m'expliquer, en gros la position des touches sur nos claviers sont différentes (moi j'Aiclavier canadien multilingue, toi t'a un clavier français j'me trompe ?), donc en fait si je veux modifier d'avance les configs des mods et des touches, pour pas que l'utilisateur aille tout a configurer lui même, ben ça pause problème, seules solutions : Créer plusieurs dossier sync (ce qui rendrait la modification du modpack beaucoup plus longue) ou ajouter un système d'options configurable par le créateur du modpack a l'intérieur de l'installateur (donc les utilisateurs pourront, en gros choisir quoi télécharger). J'me suis bien expliquer ?

**Comment by robin4002** [comment]
En effet c'est plus clair. Mais je ne vois pas trop l'utilité, en général après l'installation d'un jeu n'importe qui configure les touches dans un premier temps, non ?
Et puis ça va être complexe à mettre en place, faut que je reflechisse à comment faire ça.
En plus les touches sont dans le fichier options.txt et non dans le dossier config.

**Comment by vrackfall** [comment]
Ouai bon, mais la c'est pas n'importe quel jeu c'est mc, donc c'est différent (en vanilla les joueurs n'ont pratiquement rien a configurer, car lkes touches sont configurer automatiquement non ?), et comme tu dit c'est pas tant pour le dossier config et sinon j'ai déjà quelques idées de comment ça pourrait marcher mais pour le code .... , sinon j'viens d'avoir une autre idée pour certains mods (comme battlemusic), leurs configs et fichiers sont installés a la racine du .minecraf même s'ils font partis d'un modpack (dans le cas de battlemusic, un dossier qui contient des pack de music), tu comprend ou j'veux en venir ? Il faudrait que les fichiers/dossiers de ces mods soit installés automatiquement a la racine du jeux.

**Comment by utybo** [comment]
"en vanilla les joueurs n'ont pratiquement rien a configurer, car lkes touches sont configurer automatiquement non ?"

Non. Les touches sont en QWERTY d'origine et doivent être modifiées en AZERTY. Donc, en France au moins, tout le monde modifie les touches.

**Comment by vrackfall** [comment]
Ha ouai, mais bon pour comment ça marcherais : 
on rajoute un dossier option au dossier sync avant d'y mettre par exemple 4 dossiers pour 4 options
![options](https://cloud.githubusercontent.com/assets/9774420/8633911/098e8a28-27b1-11e5-8535-afbc681eaa03.PNG)

**Comment by robin4002** [comment]
Le problème avec une implémentation de ce type c'est que le système de synchronisation n'est pas du tout prévu pour. À  chaque fois que tu vas lancer le jeu il va retélécharger les config si je fais ça. Donc il faudrait modifier en plus le système actuel de synchronisation.
À la limite faudrait faire un fichier options_azerty.txt et un dossier options_qwezrty quelque part qu'il ne télécharge que la première fois. Ça en revanche c'est plus faisable. Il est surement possible de détecter automatiquement le type de clavier.
Comme le fichier option.txt contient aussi les options graphiques du jeu, je pourrai cumuler l'option des touches  avec une option de graphique (genre options_low.txt ou options_high.txt) et adapter en fonction du processeur / la carte graphique de l'utilisateur (le processeur devrait être plus simple, en fonction du nombre de cœur).

Pour le problème des mods qui mettent leurs dossiers de config dans .minecraft/config au lieu de .minecraft/modpacks/nom du modpack/config, ce n'est pas de ma faute. Certains moddeurs ont la très bonne idée d'utiliser new File("."); voir récréer leurs propres fonctions pour get le .minecraft au lieu d'utiliser Minecraft.getMinecraft().mcDataDir ou une deux ces deux fonctions de FML prévu pour : https://github.com/MinecraftForge/MinecraftForge/blob/master/fml/src/main/java/net/minecraftforge/fml/common/event/FMLPreInitializationEvent.java#L70-L75
Je vais voir s'il y a moyen de hack le dossier dans lequel le jeu est lancer, ça règlera le problème des mods qui utiliser new File("."), mais je ne suis pas sûr que c'est possible.

Je garde cette idée de côté pour la v2 que vais développer pendant ces vacances, pour l'instant j'ai d'autres priorités.

**Comment by vrackfall** [comment]
Ok,  prend ton temps, mais réfléchis bien au système et essais de couvrir le plus d'options possibles (du genre y'a pas juste le fichier options.txt mais aussi d'autres fichiers par ex certain fichiers du dossier config/liteconfig qui pourraient changer s'il y'a des réfférence au clavier)
Merci d'avance

**Comment by robin4002** [comment]
liteconfig ? C'est liteloader ça ? Il sauvegarde les touches là dedans ?

**Comment by vrackfall** [comment]
Ouai, en fait c'est pour toutes les configs concernant liteloader incluant les touches des mods liteloader. Elles (les touches des mods liteloader) doivent être pareil dans le fichier config.txt et le dossier liteconfig, donc si l'un des deux est synchronisé par l'installateur l'autre doit l'être aussi (justement pour ça que mon système, que j'ai décris dans le 7ième commentaire pourrait faire parfaitement l'affaire). Je pense que j'ai tout dit, et (prend ton temps) merci d'avance

**Comment by vrackfall** [comment]
Et donc avez-vous commencez ?

**Comment by robin4002** [comment]
Non, je n'ai toujours pas commencé à travailler dessus. J'ai d'autres priorités pour l'instant.

**Comment by robin4002** [comment]
Bon j'ai finalement réfléchi a comment implémenter ça.
Dans le fichier remote_profile.json il va avoir une option en plus nommé preConfig. Il faudra mettre l'url d'un dossier dans lequel se trouvera un même fichier index.php que dans le dossier sync (pour générer un json automatiquement). Exemple : http://dl.mcnanotech.fr/FFMT/installer/demo/preConfig/
Ensuite ce qui se trouve dedans sera téléchargé lors du premier lancement de l'installateur (en fonction de l'option choisi).
L'option par défaut devra être spécifié dans le fichier remote_profile.json et il sera possible de changer à l'aide de bouton option de l'installateur.

Maintenant il me reste à coder ça.

**Comment by vrackfall** [comment]
Ouai, bonne chance.

**Comment by robin4002** [comment]
https://github.com/FFMT/ModPackInstaller/commit/8f4399ecb08f8af42cdfee8e8371242432327126

**Comment by vrackfall** [comment]
Wow, trop cool, j'viens de le compiler, 
![ffmt-installer-2 0](https://cloud.githubusercontent.com/assets/9774420/11746045/efc92b3c-9fe9-11e5-8712-084d74459301.PNG)

**Comment by robin4002** [comment]
Je compte faire la release une documentation ce week-end.
Si tu veux les fichiers php sont dispo dans le dossier php (pour générer les jsons, il faut juste modifier le php pour les preconfig afin de définir la configuration par défaut). Pour le fichier remote_profile tu peux reprendre celui de démonstration (dispo ici : http://dl.mcnanotech.fr/FFMT/installer/demo/remote_info.json) 
Pareil pour le changelog, il y a un exemple ici : http://dl.mcnanotech.fr/FFMT/installer/demo/changelog.json

**Comment by vrackfall** [comment]
Ok merci, j'vais p'tre pouvoir t'aider pour la docu. 
Mais le dossier preset, il marche comment ? Je sais juste mettre ce que je veux dedans ?

**Comment by vrackfall** [comment]
Ah et dans la docu faudra pas oublier de préciser ça : 
Installation
...
#-Placer les fichiers index_preset.php et index_sync.php dans leurs dossiers respectifs de votre site web, puis les renommer en index.php
...
