### ISSUE TITLE
Problème installation Flan

### ISSUE THREAD

**Issue by Arroy3876** [FFMT/ModPackInstaller#8]
Avec un dossier Flan dans le ModPack l’installateur signale une erreur : https://gyazo.com/329e6e7d55c1326bdb6543050e875221 .

Voilà le lien des dossiers : http://armamania.fr/Instalateur/

Cordialement.

**Comment by robin4002** [comment]
Bonsoir,
Essaies de renommer le dossier "Powers's Content Pack V4.4" en "Powers s Content Pack V4.4"
Je pense que l'apostrophe cause problème.

**Comment by Arroy3876** [comment]
Merci de ta réponse pour que cela marche j'ai du enlever les espaces et les apostrophes.

Merci a toi.

**Comment by robin4002** [comment]
Les espaces aussi ?
Je fais voir pour corriger ça dans la version 2.0. J'ai du oublié de gérer l'encodage des url des dossier, car celui des noms de fichier c'est fonctionnel.

**Comment by robin4002** [comment]
à partir de la version 2.0 il ne sera plus nécessaire de renommer les dossiers avec espace.
